cloud:
  aws:
    credentials:
      access-key: AKIAW4TCMVZQFTZGJNV4
      secret-key: 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
    region:
      static: eu-central-1
    stack:
      auto: false

application:
  bucket:
    name: beedevstorage


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080
